const { MongoClient } = require('mongodb');
require('dotenv').config();

const uri = process.env.MONGO_DB_URI;
const client = new MongoClient(uri);

async function seed() {
  try {
    await client.connect();
    console.log('Connected to MongoDB');

    const db = client.db('fitpulse');
    const classCollection = db.collection('classes');
    const forumPostCollection = db.collection('forumPosts');

    const classes = [
      {
        className: 'Inferno HIIT: Full-Body Fire',
        authorName: 'Alex Rivera',
        authorEmail: 'alex.rivera@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=alex',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800',
        category: 'hiit',
        difficulty: 'advanced',
        duration: 45,
        price: 35,
        schedule: ['Monday', 'Wednesday', 'Friday'],
        startTime: '06:00 AM',
        description: 'Inferno HIIT is our signature high-intensity interval training program engineered to maximize caloric burn and cardiovascular conditioning in just 45 minutes. This session alternates between explosive plyometric exercises — including box jumps, burpee variations, and battle rope waves — and active recovery periods designed to keep your heart rate elevated throughout. Each round targets a different energy system, ensuring both aerobic and anaerobic pathways are fully engaged. We incorporate timed intervals using the Tabata protocol (20 seconds work, 10 seconds rest) for the first half, followed by longer EMOM (Every Minute on the Minute) challenges for the second half. Expect to move through squat thrusts, kettlebell swings, sled pushes, and agility ladder drills. This class demands prior HIIT experience; modifications are minimal to maintain intensity. Athletes should arrive hydrated, bring a towel, and prepare to leave everything on the floor. Post-class stretching and mobility drills are included in the final 5 minutes to support recovery and reduce injury risk.',
        status: 'Approved',
        totalEnrollment: 47,
        capacity: 30,
        createdAt: new Date('2025-01-15'),
      },
      {
        className: 'Vinyasa Flow: Sunrise Yoga',
        authorName: 'Maya Chen',
        authorEmail: 'maya.chen@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=maya',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800',
        category: 'yoga',
        difficulty: 'beginner',
        duration: 60,
        price: 20,
        schedule: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
        startTime: '07:00 AM',
        description: 'Start your morning with our Sunrise Vinyasa Flow, a gently dynamic yoga practice designed to awaken the body and calm the mind. This 60-minute session guides you through a seamless sequence of postures linked by breath — from foundational Sun Salutations (Surya Namaskar) to standing poses, balancing postures, and a restorative cool-down. Our certified instructor emphasizes proper alignment and mindful transitions, making this class accessible to beginners while offering depth for experienced practitioners. You will explore poses such as Downward-Facing Dog, Warrior I and II, Triangle Pose, Tree Pose, and Seated Forward Fold, each held with intentional breathing to deepen the stretch and build internal heat. The class culminates in a guided savasana and brief meditation to center your focus for the day ahead. No prior yoga experience is required. Please bring your own mat and wear comfortable, stretchable clothing. Props such as blocks and straps are available at the studio. This practice builds flexibility, core stability, and mental resilience — a holistic start to any morning.',
        status: 'Approved',
        totalEnrollment: 82,
        capacity: 40,
        createdAt: new Date('2025-01-20'),
      },
      {
        className: 'Iron Asylum: Powerlifting Fundamentals',
        authorName: 'Marcus Steele',
        authorEmail: 'marcus.steele@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=marcus',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800',
        category: 'weights',
        difficulty: 'intermediate',
        duration: 75,
        price: 40,
        schedule: ['Tuesday', 'Thursday', 'Saturday'],
        startTime: '09:00 AM',
        description: 'Iron Asylum is a comprehensive powerlifting program focused on mastering the Big Three lifts: squat, bench press, and deadlift. This 75-minute session is structured around progressive overload principles, starting with a dynamic warm-up that primes the nervous system and mobilizes key joints. The main working block targets one primary lift each session, complemented by accessory movements that address weak points and improve overall strength. You will learn proper bracing techniques, bar path optimization, and breathing patterns to maximize output while minimizing injury risk. Our experienced coach provides individualized feedback through video analysis and hands-on adjustments. Each session concludes with core work and mobility drills tailored to powerlifters. This class is designed for individuals who have completed at least three months of consistent resistance training and can demonstrate basic proficiency with barbell movements. Required equipment includes lifting shoes, a belt, and wrist wraps if you have them. All other specialty equipment such as knee sleeves, chalk, and resistance bands are provided. Join us to build raw strength, improve your numbers, and become part of a community that celebrates progress.',
        status: 'Approved',
        totalEnrollment: 38,
        capacity: 20,
        createdAt: new Date('2025-02-01'),
      },
      {
        className: 'Cardio Inferno: Endurance Engine',
        authorName: 'Sarah Mitchell',
        authorEmail: 'sarah.mitchell@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=sarah',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800',
        category: 'cardio',
        difficulty: 'intermediate',
        duration: 50,
        price: 25,
        schedule: ['Monday', 'Wednesday', 'Friday'],
        startTime: '08:00 AM',
        description: 'Endurance Engine is a high-energy cardiovascular conditioning class that blends steady-state and interval training to boost your aerobic capacity and stamina. Over 50 minutes, you will rotate through stations featuring rowing machines, assault bikes, jump ropes, and treadmill sprints, each designed to challenge your heart and lungs from multiple angles. The class is structured into three phases: a dynamic warm-up focusing on mobility and activation, a main set of 4 x 8-minute interval blocks with varying intensities, and a cool-down that incorporates light jogging and static stretching. Heart rate monitoring is encouraged to ensure you train in the appropriate zones for maximum cardiovascular adaptation. Our instructors provide real-time motivation and technique corrections to keep you moving efficiently. This class is ideal for runners, cyclists, and anyone looking to improve their overall cardiovascular health. Modifications are available for all fitness levels, but participants should be comfortable with sustained physical activity for extended periods. Bring a water bottle and a sweat towel — you will need both.',
        status: 'Approved',
        totalEnrollment: 61,
        capacity: 35,
        createdAt: new Date('2025-02-10'),
      },
      {
        className: 'Pilates Core Control',
        authorName: 'Elena Vasquez',
        authorEmail: 'elena.vasquez@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=elena',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800',
        category: 'pilates',
        difficulty: 'beginner',
        duration: 50,
        price: 22,
        schedule: ['Tuesday', 'Thursday', 'Sunday'],
        startTime: '10:00 AM',
        description: 'Core Control is a mat-based Pilates class that focuses on building deep abdominal strength, improving postural alignment, and enhancing body awareness. Using the classical Pilates principles of concentration, control, centering, precision, breath, and flow, this 50-minute session takes you through a carefully sequenced series of exercises targeting the transverse abdominis, obliques, pelvic floor, and spinal stabilizers. Movements include the Hundred, Roll-Up, Single-Leg Circles, Criss-Cross, Teaser, and Saw, each performed with deliberate tempo and breath coordination. We also incorporate small props such as resistance bands, magic circles, and foam rollers to increase resistance and proprioceptive challenge. This class is suitable for all levels — beginners will learn foundational form while advanced participants can explore deeper ranges of motion and increased repetitions. Pilates is particularly beneficial for individuals recovering from lower back injuries, those seeking to complement their athletic training with core stability work, or anyone wanting to develop a stronger mind-body connection. Please arrive a few minutes early to set up your mat and props. No previous Pilates experience is necessary.',
        status: 'Approved',
        totalEnrollment: 55,
        capacity: 25,
        createdAt: new Date('2025-02-15'),
      },
      {
        className: 'Kettlebell Assault: Strength & Conditioning',
        authorName: 'Alex Rivera',
        authorEmail: 'alex.rivera@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=alex',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c2?w=800',
        category: 'hiit',
        difficulty: 'intermediate',
        duration: 50,
        price: 30,
        schedule: ['Tuesday', 'Thursday'],
        startTime: '05:30 PM',
        description: 'Kettlebell Assault combines the explosive power of kettlebell training with metabolic conditioning to deliver a full-body workout that builds functional strength and cardiovascular endurance simultaneously. This 50-minute session progresses through a series of compound movements including swings, cleans, snatches, Turkish get-ups, and goblet squats, each performed with emphasis on hip drive, core engagement, and controlled momentum. The class is structured in AMRAP (As Many Rounds As Possible) and EMOM (Every Minute On the Minute) formats, keeping intensity high and rest periods minimal. Our coach breaks down each movement pattern with detailed instruction, ensuring proper technique before increasing load or speed. You will learn how to generate power from your posterior chain, stabilize your shoulders under load, and transition smoothly between exercises. Kettlebells ranging from 12kg to 32kg are available to accommodate different strength levels. Prior experience with kettlebell training is recommended but not required — a foundations assessment will be conducted during the first session. This class delivers serious results in strength, grip endurance, and metabolic conditioning. Come ready to work.',
        status: 'Approved',
        totalEnrollment: 33,
        capacity: 20,
        createdAt: new Date('2025-03-01'),
      },
      {
        className: 'Restorative Yoga: Deep Release',
        authorName: 'Maya Chen',
        authorEmail: 'maya.chen@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=maya',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
        category: 'yoga',
        difficulty: 'beginner',
        duration: 75,
        price: 18,
        schedule: ['Wednesday', 'Sunday'],
        startTime: '06:00 PM',
        description: 'Deep Release is a restorative yoga practice designed to activate the parasympathetic nervous system and promote profound relaxation. Unlike more active yoga styles, this 75-minute class uses bolsters, blankets, blocks, and straps to support the body in passive poses held for 5 to 10 minutes each, allowing connective tissues to lengthen and the mind to settle into stillness. The sequence includes supported child pose, legs-up-the-wall, reclined bound angle, supported bridge, and a fully guided savasana with body scan meditation. Each pose is carefully constructed to release tension stored in the hips, lower back, shoulders, and neck — areas where stress accumulates most. Our instructor provides hands-on adjustments and aromatherapy with lavender essential oil to deepen the relaxation response. This class is ideal for anyone experiencing high stress levels, recovering from intense training, or dealing with chronic pain conditions. No flexibility or prior yoga experience is required; the entire practice is designed to meet you exactly where you are. Wear warm, comfortable clothing as body temperature drops during prolonged stillness. Props are provided by the studio. Leave feeling renewed, centered, and deeply rested.',
        status: 'Approved',
        totalEnrollment: 44,
        capacity: 25,
        createdAt: new Date('2025-03-05'),
      },
      {
        className: 'Functional Strongman: Real-World Power',
        authorName: 'Marcus Steele',
        authorEmail: 'marcus.steele@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=marcus',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800',
        category: 'weights',
        difficulty: 'advanced',
        duration: 80,
        price: 45,
        schedule: ['Monday', 'Wednesday', 'Friday'],
        startTime: '06:00 PM',
        description: 'Functional Strongman is an advanced strength and conditioning program that draws from strongman training methodologies to build practical, real-world power. This 80-minute session incorporates tire flips, farmer walks, sandbag carries, axle bar deadlifts, log press, and sled dragging — movements that challenge the body in three dimensions and develop grip strength, core stability, and explosive power that traditional weightlifting cannot replicate. Each class begins with a neural activation warm-up including band work, crawls, and light carries to prepare the central nervous system. The main working block rotates through a strength circuit and a conditioning finisher, with emphasis on safe loading patterns and progressive overload. Our coach provides detailed instruction on each implement, including grip positioning, bracing strategies, and pacing. This class is designed for experienced lifters who have a solid foundation in basic barbell movements and are looking to break through plateaus. Strongman training has been shown to improve bone density, tendon strength, and metabolic conditioning more effectively than conventional resistance training. All implements and protective gear are provided. Prior consultation with the coach is recommended before your first session to assess readiness and set appropriate loading parameters.',
        status: 'Approved',
        totalEnrollment: 22,
        capacity: 15,
        createdAt: new Date('2025-03-10'),
      },
      {
        className: 'Spin to Win: Indoor Cycling',
        authorName: 'Sarah Mitchell',
        authorEmail: 'sarah.mitchell@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=sarah',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=800',
        category: 'cardio',
        difficulty: 'intermediate',
        duration: 45,
        price: 22,
        schedule: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
        startTime: '07:00 AM',
        description: 'Spin to Win is an immersive indoor cycling experience set to curated playlists that synchronize with your pedal cadence and resistance levels. Over 45 minutes, you will journey through a series of terrain simulations — flat roads, rolling hills, steep climbs, and sprint intervals — each designed to target different energy systems and muscle fibers. Our certified instructor guides you through proper bike setup, pedal technique, and breathing rhythms to maximize efficiency and power output. The class uses RPM-based metrics and perceived exertion scales so you can train at your optimal intensity regardless of fitness level. Data from the bike console including distance, calories burned, and power output is displayed in real time. The dark, candlelit studio with dynamic LED lighting creates an atmosphere that keeps you focused and motivated throughout the ride. This class is suitable for all fitness levels; resistance can be adjusted independently, and modifications for seated vs. standing climbs are demonstrated throughout. Arrive 10 minutes early for bike fitting. Sweat towels and water refill stations are available. Expect to burn 400-600 calories per session while building lower body strength and cardiovascular endurance.',
        status: 'Approved',
        totalEnrollment: 73,
        capacity: 30,
        createdAt: new Date('2025-03-15'),
      },
      {
        className: 'Mobility Lab: Movement Health',
        authorName: 'Elena Vasquez',
        authorEmail: 'elena.vasquez@fitpulse.com',
        authorImage: 'https://i.pravatar.cc/150?u=elena',
        authorRole: 'trainer',
        coverImage: 'https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=800',
        category: 'pilates',
        difficulty: 'beginner',
        duration: 55,
        price: 20,
        schedule: ['Monday', 'Wednesday', 'Friday'],
        startTime: '12:00 PM',
        description: 'Mobility Lab is a dedicated movement health class focused on improving joint range of motion, tissue quality, and movement efficiency through evidence-based mobility and flexibility techniques. This 55-minute session draws from functional range conditioning (FRC), myofascial release, dynamic stretching, and controlled articular rotations (CARs) to systematically address stiffness and movement dysfunction. Each class targets a specific region of the body on a rotating schedule — hips and spine on Mondays, shoulders and thoracic cage on Wednesdays, and full-body integration on Fridays. You will learn self-assessment techniques to identify your personal mobility limitations and track progress over time. Tools such as lacrosse balls, foam rollers, resistance bands, and yoga blocks are used to perform targeted tissue work and joint distraction. The class also includes breathing drills and nervous system regulation techniques to enhance mobility gains. This class is essential for anyone who sits at a desk for extended periods, experiences joint stiffness or discomfort during training, or wants to prevent injuries before they happen. Athletes of all levels will benefit from improved movement quality and reduced recovery time. All equipment is provided. Wear comfortable clothing that allows for a full range of motion.',
        status: 'Approved',
        totalEnrollment: 39,
        capacity: 30,
        createdAt: new Date('2025-03-20'),
      },
    ];

    const forumPosts = [
      {
        title: 'Optimizing Your Pre-Workout Nutrition for Maximum Performance',
        authorEmail: 'alex.rivera@fitpulse.com',
        authorName: 'Alex Rivera',
        authorImage: 'https://i.pravatar.cc/150?u=alex',
        role: 'trainer',
        category: 'nutrition',
        image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
        description: 'What you eat before a workout can make or break your performance. In this detailed guide, I break down the science of pre-workout nutrition and share strategies that have worked for my clients. The key principles are timing, macronutrient composition, and individual tolerance. Ideally, you want to consume a meal containing complex carbohydrates and moderate protein approximately 2-3 hours before training. This allows for adequate digestion while ensuring glycogen stores are topped off. Good options include oatmeal with whey protein and berries, whole grain toast with almond butter and banana, or Greek yogurt with granola and honey. If you are training early in the morning and cannot eat a full meal, opt for a smaller snack 30-60 minutes prior such as a piece of fruit with a small serving of nuts or a half-serving of your favorite protein shake. Fasted training can be effective for some individuals, particularly for low-intensity steady-state cardio, but for high-intensity resistance training, having fuel available significantly improves performance and reduces muscle breakdown. Hydration is equally critical — aim for 500-600ml of water in the 2-3 hours before exercise, and consider adding electrolytes if you are a heavy sweater or training in hot conditions. Avoid high-fat and high-fiber foods immediately before workouts as they slow digestion and can cause gastrointestinal discomfort. Caffeine, consumed 30-60 minutes before exercise, has well-documented ergogenic effects including improved focus, reduced perceived exertion, and increased power output. Start with a modest dose of 1-2mg per kg of body weight and adjust based on your tolerance. Remember that individual responses vary significantly, so experiment during lower-priority training sessions before implementing changes on competition or max-effort days. Listen to your body, keep a food and performance log, and adjust based on what works best for you.',
        createdAt: new Date('2025-03-25'),
        likes: ['user1@test.com', 'user2@test.com', 'user3@test.com'],
        dislikes: [],
        commentCount: 7,
      },
      {
        title: 'The Science of Recovery: Why Rest Days Are Non-Negotiable',
        authorEmail: 'maya.chen@fitpulse.com',
        authorName: 'Maya Chen',
        authorImage: 'https://i.pravatar.cc/150?u=maya',
        role: 'trainer',
        category: 'recovery',
        image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
        description: 'In the fitness world, we often celebrate the grind — the early morning sessions, the pushed-through fatigue, the extra rep when everything in you wants to stop. But what we do between workouts is just as important as what we do during them. Recovery is not a sign of weakness; it is a physiological necessity. When you train, you create micro-tears in muscle fibers and deplete your nervous system. Growth and adaptation happen during rest, when your body repairs those tears and builds back stronger. Without adequate recovery, you enter a state of diminishing returns where performance plateaus, injury risk skyrockets, and hormonal balance suffers. This post covers the key pillars of effective recovery: sleep (aim for 7-9 hours of quality sleep per night — this is when growth hormone secretion peaks and tissue repair occurs at its highest rate), active recovery (light activities like walking, swimming, or gentle yoga on rest days promote blood flow and nutrient delivery to recovering tissues without adding significant stress), nutrition (post-workout meals should include protein to support muscle protein synthesis and carbohydrates to replenish glycogen stores; timing within the 30-60 minute anabolic window is beneficial but not as critical as total daily intake), stress management (chronic elevated cortisol impairs recovery and can lead to overtraining syndrome; incorporate meditation, deep breathing, or other relaxation practices), and hydration (even mild dehydration impairs performance and slows recovery). Signs that you may need more recovery include persistent fatigue, decreased performance, mood disturbances, increased resting heart rate, and frequent illness. Learn to distinguish between the productive discomfort of training and the warning signals of overreaching. Your body is your most important training partner — treat it with respect.',
        createdAt: new Date('2025-03-26'),
        likes: ['user1@test.com', 'user4@test.com', 'user5@test.com', 'user6@test.com'],
        dislikes: ['user7@test.com'],
        commentCount: 12,
      },
      {
        title: 'Programming for Hypertrophy: Volume, Intensity, and Frequency Demystified',
        authorEmail: 'marcus.steele@fitpulse.com',
        authorName: 'Marcus Steele',
        authorImage: 'https://i.pravatar.cc/150?u=marcus',
        role: 'trainer',
        category: 'training',
        image: 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=800',
        description: 'Building muscle is both an art and a science. After a decade of coaching athletes from beginners to competitive bodybuilders, I have distilled the fundamentals of hypertrophy programming into three key variables: volume, intensity, and frequency. Volume refers to the total amount of work performed, typically measured in sets per muscle group per week. Research consistently shows that 10-20 working sets per muscle group per week produces optimal hypertrophic responses in most individuals. Beginners should start at the lower end of this range and progressively add volume as they become more adapted to training. Intensity is about how close you train to muscular failure. While training to absolute failure on every set is not necessary and may impede recovery, working within 1-3 reps of failure on most sets seems to maximize muscle fiber recruitment and metabolic stress. The final 3-5 reps before failure are where the majority of hypertrophic stimulus occurs, regardless of the absolute load. Frequency refers to how often you train each muscle group per week. Current evidence supports training each muscle group 2-3 times per week for optimal hypertrophy, as this allows for more consistent protein synthesis stimulation and better distribution of training volume. A well-structured push-pull-legs or upper-lower split can accomplish this efficiently. Beyond these variables, exercise selection matters. Prioritize compound movements (squat, bench press, deadlift, overhead press, rows, pull-ups) for overall mass and mechanical tension, then supplement with isolation exercises (bicep curls, tricep extensions, lateral raises, leg curls, calf raises) to target specific muscle groups and add volume. Progressive overload remains the non-negotiable foundation — you must consistently challenge your muscles with increasing demands over time, whether through added weight, more reps, reduced rest intervals, or improved form and mind-muscle connection.',
        createdAt: new Date('2025-03-27'),
        likes: ['user1@test.com', 'user2@test.com', 'user8@test.com'],
        dislikes: [],
        commentCount: 15,
      },
      {
        title: 'Meal Prep Mastery: A Week of High-Protein, Nutrient-Dense Meals',
        authorEmail: 'sarah.mitchell@fitpulse.com',
        authorName: 'Sarah Mitchell',
        authorImage: 'https://i.pravatar.cc/150?u=sarah',
        role: 'trainer',
        category: 'nutrition',
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        description: 'Meal prepping is the single most effective strategy for maintaining consistent nutrition throughout a busy week. When your refrigerator is stocked with ready-to-eat, portion-controlled meals, the likelihood of reaching for convenient but nutritionally poor options drops dramatically. In this guide, I walk through my weekly meal prep system that takes about 2-3 hours on Sunday and sets me up for success Monday through Friday. Start with a protein base: grill 2-3 pounds of chicken breast seasoned with garlic, paprika, and herbs; prepare a batch of lean ground turkey or beef with taco seasoning; and hard-boil a dozen eggs for quick snacks. For carbohydrates, choose complex sources that provide sustained energy: cook a large batch of quinoa or brown rice, roast sweet potatoes and regular potatoes with olive oil and rosemary, and prep steel-cut oats that can be reheated with protein powder and berries in the morning. Vegetables should fill half your plate: roast a sheet pan of broccoli, bell peppers, zucchini, and cherry tomatoes drizzled with balsamic vinegar; prepare a large salad base of mixed greens with cucumber, cherry tomatoes, and a homemade vinaigrette (olive oil, apple cider vinegar, Dijon mustard, and herbs); and steam or sauté spinach and kale for quick sides. Healthy fats come from avocado (store with the pit to prevent browning), almonds and walnuts (portion into small bags), chia seeds and flaxseed for smoothies, and olive oil used in cooking and dressings. Sample day structure: breakfast is overnight oats with protein powder, berries, and almond butter; lunch is grilled chicken breast with quinoa, roasted vegetables, and avocado slices; afternoon snack is Greek yogurt with berries and a hard-boiled egg; dinner is turkey chili with sweet potato and a side salad; evening snack is cottage cheese with flaxseed and cinnamon. Portion everything into glass containers labeled by day. This system has helped dozens of my clients maintain consistent nutrition while reducing decision fatigue and saving significant time during the week.',
        createdAt: new Date('2025-03-28'),
        likes: ['user3@test.com', 'user5@test.com', 'user9@test.com'],
        dislikes: [],
        commentCount: 9,
      },
      {
        title: 'Mobility Work for Lifters: Opening Your Hips and Thoracic Spine',
        authorEmail: 'elena.vasquez@fitpulse.com',
        authorName: 'Elena Vasquez',
        authorImage: 'https://i.pravatar.cc/150?u=elena',
        role: 'trainer',
        category: 'training',
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800',
        description: 'As a strength coach, the most common limitations I see in lifters are not in their strength but in their mobility. Tight hips and a stiff thoracic spine are epidemic among people who spend significant time sitting during the day and training in sagittal-plane movements like squats and deadlifts. The consequences are predictable: low back pain, inefficient movement patterns, and increased injury risk. Fortunately, these issues are highly correctable with consistent mobility work. For hip mobility, focus on opening the anterior capsule and improving rotational capacity. The couch stretch is my go-to anterior hip opener — kneel with your back foot against a wall and drive your hips forward while keeping your torso upright. Hold for 2-3 minutes per side, breathing deeply into the front of the hip. For rotational mobility, the 90-90 hip stretch is excellent: sit with both knees bent at 90 degrees, one leg in front and one behind, then gently lean your torso toward the front leg. Add a thoracic rotation component by placing your opposite hand behind your head and rotating toward the ceiling. For the thoracic spine, you need extension, rotation, and side-bending capacity. Using a foam roller placed perpendicular to your spine at the level of the shoulder blades, perform 10-15 slow extensions allowing your head to drop toward the floor. Follow this with open-book thoracic rotations lying on your side with knees bent, arms extended in front, and slowly rotating your top arm to open toward the ceiling while keeping your hips stable. Quadruped thoracic rotations with your hand behind your head are also highly effective. Perform these drills daily, ideally before training as part of your warm-up. Spend 5-10 minutes and you will notice improvements in your squat depth, overhead position, and overall comfort under load within two weeks.',
        createdAt: new Date('2025-04-01'),
        likes: ['user1@test.com', 'user6@test.com', 'user10@test.com'],
        dislikes: ['user2@test.com'],
        commentCount: 11,
      },
      {
        title: 'Announcement: New Outdoor Training Pavilion Coming to FitPulse',
        authorEmail: 'sarah.mitchell@fitpulse.com',
        authorName: 'Sarah Mitchell',
        authorImage: 'https://i.pravatar.cc/150?u=sarah',
        role: 'trainer',
        category: 'announcement',
        image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800',
        description: 'We are thrilled to announce that construction of our new Outdoor Training Pavilion will be completed by the end of next month. This 3,500-square-foot covered training space will allow us to expand our class offerings and provide a unique outdoor training experience protected from the elements. The pavilion features a reinforced concrete foundation suitable for all types of training including Olympic lifting, strongman implements, and high-intensity interval circuits. It is equipped with heavy-duty rigging for gymnastics rings, battle rope anchors, and suspension trainers, as well as dedicated platform space for barbell work. The perimeter is lined with artificial turf for sled work, agility drills, and bodyweight conditioning. We have installed industrial-grade fans for air circulation and overhead LED lighting for evening sessions. The pavilion will host a new roster of classes including Outdoor HIIT, Turf Wars (a team-based functional fitness competition), and Saturday Morning Strongman sessions. Existing classes will also rotate outdoor sessions when weather permits. We are scheduling a grand opening event on the first Saturday of next month featuring free trial classes, equipment demonstrations, a nutrition booth with sample meals from our partner kitchen, and a community barbecue. All members are invited, and we encourage you to bring a friend who might be interested in joining the FitPulse community. Class schedules will be updated in the app and on our website within two weeks, and early registration for outdoor pavilion classes opens next Monday at 9AM. Spaces will be limited to maintain quality coaching ratios. We cannot wait to train with you under the open sky. Stay tuned for more updates and construction progress photos on our social media channels.',
        createdAt: new Date('2025-04-03'),
        likes: ['user1@test.com', 'user2@test.com', 'user3@test.com', 'user4@test.com', 'user5@test.com'],
        dislikes: [],
        commentCount: 24,
      },
      {
        title: 'Deload Weeks: How and When to Pull Back for Long-Term Gains',
        authorEmail: 'alex.rivera@fitpulse.com',
        authorName: 'Alex Rivera',
        authorImage: 'https://i.pravatar.cc/150?u=alex',
        role: 'trainer',
        category: 'training',
        image: 'https://images.unsplash.com/photo-1571942676516-bcab84649e44?w=800',
        description: 'Every few weeks, I get asked the same question from athletes: "Do I really need to take a deload week?" My answer is always the same: yes, if you want to keep making progress. A deload is a planned period of reduced training volume and intensity that allows your body and nervous system to fully recover from accumulated training stress. Think of it as a strategic reset rather than a step backward. The general guideline is to deload every 4-6 weeks of consistent training, but this varies based on training intensity, volume, individual recovery capacity, age, sleep quality, and overall life stress. Signs that you are overdue for a deload include plateauing or decreasing performance, persistent muscle soreness that does not resolve with normal recovery, elevated resting heart rate, poor sleep quality, increased irritability or mood swings, loss of training motivation, and increased frequency of minor injuries or illnesses. How to structure a deload: reduce training volume by 40-60% while keeping intensity (weight on the bar) at 70-80% of your working weights. The key is to maintain movement patterns and neuromuscular coordination without accumulating significant fatigue. Drop sets per exercise from 4 to 2, reduce training frequency if needed, and eliminate accessory work to focus on main lifts only. Alternatively, you can take a full week off from structured training and engage in enjoyable physical activities like hiking, swimming, recreational sports, or yoga. Many athletes return from deload weeks setting new personal records because they allowed their systems to supercompensate. Do not view deloads as lost time; view them as investments in your future progress. The athletes who train hardest are often the ones who need deloads most. Be smart, be patient, and trust the process.',
        createdAt: new Date('2025-04-05'),
        likes: ['user7@test.com', 'user8@test.com', 'user9@test.com'],
        dislikes: [],
        commentCount: 8,
      },
      {
        title: 'Plant-Based Eating for Athletic Performance: Separating Fact from Fiction',
        authorEmail: 'maya.chen@fitpulse.com',
        authorName: 'Maya Chen',
        authorImage: 'https://i.pravatar.cc/150?u=maya',
        role: 'trainer',
        category: 'nutrition',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        description: 'There is a persistent myth in the fitness industry that animal protein is essential for building muscle and performing at a high level. As a certified sports nutritionist who has worked with vegan and vegetarian athletes ranging from recreational lifters to competitive CrossFit athletes, I am here to tell you that plant-based eating can absolutely support elite performance when properly planned. The key concerns with plant-based athletic nutrition are protein quantity and quality, creatine intake, vitamin B12, iron, omega-3 fatty acids, and total calorie sufficiency. Let me address each. Protein: Combine complementary plant proteins throughout the day to ensure a complete amino acid profile. Foods like lentils, chickpeas, quinoa, tofu, tempeh, seitan, edamame, and hemp seeds are excellent sources. Aim for 1.6-2.2g of protein per kg of body weight, the same range recommended for omnivorous athletes. Supplementing with pea and rice protein blends can help meet higher targets conveniently. Creatine: While creatine is naturally found in animal tissues, creatine monohydrate supplements are vegan-friendly and highly effective for improving power output and lean mass gains. B12: This essential vitamin is not naturally present in plant foods, so supplementation is mandatory for vegans. A sublingual methylcobalamin supplement of 1000mcg per day is standard. Iron: Plant-based iron (non-heme) is less bioavailable than heme iron from animals, so vegans should aim for 1.8 times the standard RDA. Pair iron-rich foods like spinach, lentils, and fortified cereals with vitamin C sources (citrus, bell peppers, tomatoes) to enhance absorption. Omega-3s: Algae-based DHA/EPA supplements provide the same long-chain fatty acids found in fish oil without the environmental concerns. Calorie sufficiency: Plant foods are often less calorie-dense than animal products, so athletes may need to eat larger volumes or include more calorie-dense whole foods like nuts, seeds, avocados, and coconut to meet energy demands. Many of my plant-based athletes report improved recovery, better digestion, and more consistent energy levels once they dial in these fundamentals. With thoughtful planning, a plant-based diet can fully support athletic goals.',
        createdAt: new Date('2025-04-07'),
        likes: ['user2@test.com', 'user4@test.com', 'user6@test.com', 'user10@test.com'],
        dislikes: ['user3@test.com'],
        commentCount: 19,
      },
      {
        title: 'Breathwork for Athletes: Techniques to Improve Performance and Manage Stress',
        authorEmail: 'elena.vasquez@fitpulse.com',
        authorName: 'Elena Vasquez',
        authorImage: 'https://i.pravatar.cc/150?u=elena',
        role: 'trainer',
        category: 'recovery',
        image: 'https://images.unsplash.com/photo-1506126279646-a697353d3166?w=800',
        description: 'Breathing is the most fundamental physiological process we have, yet most athletes never train it intentionally. Proper breathwork can improve athletic performance, accelerate recovery, and manage competition anxiety more effectively than many supplements. This post covers three breathwork techniques with specific applications for athletes. First, diaphragmatic breathing (belly breathing) is the foundation. Most adults are shallow chest breathers due to chronic stress and poor postural habits. To retrain the diaphragm, lie on your back with one hand on your chest and one on your belly. Inhale slowly through your nose for 4 seconds, feeling your belly rise while your chest remains relatively still. Exhale through your mouth for 6 seconds, feeling your belly fall. Practice for 5 minutes daily, gradually extending the exhale to 8 seconds. This activates the vagus nerve and shifts your autonomic nervous system toward parasympathetic dominance. Second, the Wim Hof breathing method involves cycles of 30-40 deep rapid breaths followed by breath retention. This technique increases blood oxygenation, alkalizes blood pH, and has been shown to reduce inflammation and improve immune function. Use this before training sessions requiring high anaerobic output or as part of your morning routine. Third, box breathing (4-4-4-4 pattern) is the gold standard for performance anxiety management. Inhale for 4 seconds, hold for 4 seconds, exhale for 4 seconds, hold empty for 4 seconds. Repeat for 3-5 minutes before competitions, heavy lifts, or any high-pressure situation. This technique stabilizes heart rate variability and improves cognitive clarity under stress. For recovery, try 4-7-8 breathing: inhale for 4 seconds, hold for 7 seconds, exhale for 8 seconds. Practice this immediately after training or before sleep to accelerate parasympathetic recovery and improve sleep quality. Consistent breathwork practice of 5-10 minutes daily yields measurable improvements in resting heart rate, heart rate variability, and perceived recovery within two weeks.',
        createdAt: new Date('2025-04-08'),
        likes: ['user1@test.com', 'user5@test.com', 'user7@test.com'],
        dislikes: [],
        commentCount: 13,
      },
      {
        title: 'FitPulse Community Challenge: 30-Day Consistency Streak',
        authorEmail: 'marcus.steele@fitpulse.com',
        authorName: 'Marcus Steele',
        authorImage: 'https://i.pravatar.cc/150?u=marcus',
        role: 'trainer',
        category: 'announcement',
        image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800',
        description: 'Starting next Monday, we are launching our biggest community challenge yet: the FitPulse 30-Day Consistency Streak. The mission is simple — train at least once every day for 30 consecutive days. But this is not about grinding yourself into the ground. The challenge is designed to build the habit of showing up, not the habit of overtraining. You decide what counts as training each day. It could be a scheduled class at FitPulse, a home workout following one of our program templates, a run or cycle outdoors, a yoga session, or even active recovery like a 30-minute walk combined with mobility work. The only rule is that you must do something intentional for at least 20 minutes every day and log it in the FitPulse app under the Challenges tab. We have built a tracking system that will show your streak, your fellow participants, and a community leaderboard organized by streaks and total activity minutes. There are milestone rewards at 7 days (FitPulse digital badge), 14 days (15% off your next class pack), 21 days (free guest pass for a friend), and the full 30 days (exclusive FitPulse 30-Day Champion t-shirt plus entry into a drawing for three months of unlimited classes). We will also have weekly check-in threads in this forum where you can share your experiences, struggles, and tips. Our coaches will post daily motivation and mini-challenges to keep things interesting. To make this sustainable, I strongly recommend incorporating at least 2-3 active recovery days per week — mobility sessions, light swimming, or even a dedicated stretching practice. The goal is to build the identity of someone who moves every day, not to accumulate fatigue. Registration opens now in the app. There is no cost to participate, and all current members are automatically eligible. Let us see what this community can do when we commit to showing up together. Who is in?',
        createdAt: new Date('2025-04-10'),
        likes: ['user1@test.com', 'user2@test.com', 'user3@test.com', 'user4@test.com'],
        dislikes: [],
        commentCount: 32,
      },
    ];

    const classResult = await classCollection.insertMany(classes);
    console.log(`✅ Inserted ${classResult.insertedCount} classes`);

    const forumResult = await forumPostCollection.insertMany(forumPosts);
    console.log(`✅ Inserted ${forumResult.insertedCount} forum posts`);

    console.log('\n🎉 Seeding complete!');
  } catch (error) {
    console.error('❌ Seeding failed:', error);
  } finally {
    await client.close();
    console.log('Disconnected from MongoDB');
  }
}

seed();
